site_name: Posterizarr
site_url: https://fscorrupt.github.io/posterizarr/
repo_url: https://github.com/fscorrupt/posterizarr
repo_name: fscorrupt/posterizarr
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo_banner.png
  favicon: images/webhook.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - header.autohide
    - search.share
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Page navigation
nav:
  - 'Home': 'index.md'
  - 'Showcase': 'showcase.md'
  - 'Getting Started':
    - 'Requirements': 'requirements.md'
    - 'Quick Start': 'installation.md'
    - 'Manual UI Installation': 'uiinstallation.md'
    - 'Walkthrough': 'walkthrough.md'
    - 'Networking': 'networking.md'
    - 'FAQs': 'faqs.md'
  - 'Configuration': 'configuration.md'
  - 'Usage & Guides':
    - 'Usage & Modes': 'modes.md'
    - 'Action Center Guide': 'action_center.md'
    - 'Blueprints & Recipes': 'blueprints.md'
    - 'Agregarr Integration': 'agregarrintegration.md'
    - 'Kometa Integration': 'kometaintegration.md'
    - 'Jellyfin Plugin': 'jellyfin_plugin.md'
    - 'Emby Plugin': 'emby_plugin.md'
    - 'Homepage Custom API': 'homepage.md'
  - 'Advanced':
    - 'Search Order': 'searchorder.md'
    - 'Naming Convention': 'namingconvention.md'
    - 'Platform & Tools': 'platformandtools.md'
    - 'API Endpoints': 'endpoints.md'
    - 'Telemetry Server': 'telemetry.md'
  - 'Developer Guide':
    - 'PowerShell Scripts': 'powershell_scripts.md'
    - 'Backend Python': 'backend_python.md'
    - 'Frontend Components': 'frontend_components.md'


# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink

# Extra features (Adapted from example)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fscorrupt
      name: GitHub Profile
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fYyJQSGt54
      name: Discord Server
    - icon: simple/kofi
      link: https://ko-fi.com/R6R81S6SC
      name: Support on Ko-fi

copyright: Copyright &copy; 2025 fscorrupt
